### ISSUE TITLE
Firmware version v1.1.0 is unverified

### ISSUE THREAD

**Issue by astuder** [astuder/tilelib#4]
We weren't able to verify this library against a Tile with firmware v1.1.0. Please let us know if you successfully used this library with that firmware version.

**Comment by vangalvin** [comment]
I purchased the new version of the Swarm Dev Kit, removed the feather and made a frakenstien adapter for a Heltec CubeCell LoRa. The tile is running 1.1.0. 

This is the response I am getting.

```
.$FV*10$DT 20210818215944,V*45
.$FV*10.$FV*10.$FV*10$GN -36.9157,174.8898,36,353,1*39
$GS 206,206,6,0,D3*45
.$FV*10$DT 20210818215959,V*49
$RT RSSI=-88*2d
$GN -36.9157,174.8898,37,353,1*38
$GS 206,206,6,0,D3*45
.$FV*10$DT 20210818220004,V*4e
$RT RSSI=-87*22
.$FV*10.$FV*10.$FV*10$GN -36.9157,174.8898,38,347,0*33
$GS 205,206,6,0,D3*46
.$FV*10$DT 20210818220019,V*42
$RT RSSI=-87*22
$GN -36.9157,174.8898,39,347,0*32
$GS 205,206,6,0,D3*46
.$FV*10$DT 20210818220024,V*4c
```
(edit formatting of log to see all characters)

**Comment by vangalvin** [comment]
I did a serial passthrough to see what was going on and $FV*10 results in
`$FV 2021-07-21-23:19:41,v1.1.0*7e`
being returned.

**Comment by astuder** [comment]
The functions that changed with Tile firmware v1.1.0 and need to be verified are:

`tile_status_t getConfig(tile_config_t &config)`
App ID should be reported as 0

`tile_status_t sendMessage(tile_send_msg_t &send_msg)`
App ID can be passed into the function via the `tile_send_msg_t` structure  and should be added to the `$TD` command unless the App ID is 0.

`tile_status_t readMessage(tile_read_msg_t &read_msg)`
App ID is returned in the `tile_read_msg_t` structure. Not sure if/how that can be entered when sending a message from the Swarm Hive portal.

The simplified `sendMessage` and `readMessage` functions should also work and under the hood use 0 as App ID.

**Comment by astuder** [comment]
Verified.
